webtalk_init -webtalk_dir Z:/rrutherford20/CS-401-1-CompArch/MIPS_1/ALU_FINAL/ALU_FINAL.sim/sim_1/behav/xsim/xsim.dir/TestALU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb 10 13:54:30 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9c3f4374-8efb-4fee-8772-5e2ddb38a779" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "855fffe6f8464741bc0494f0f7a9eb32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6104_KB" -context "xsim\\usage"
webtalk_transmit -clientid 609969841 -regid "" -xml Z:/rrutherford20/CS-401-1-CompArch/MIPS_1/ALU_FINAL/ALU_FINAL.sim/sim_1/behav/xsim/xsim.dir/TestALU_behav/webtalk/usage_statistics_ext_xsim.xml -html Z:/rrutherford20/CS-401-1-CompArch/MIPS_1/ALU_FINAL/ALU_FINAL.sim/sim_1/behav/xsim/xsim.dir/TestALU_behav/webtalk/usage_statistics_ext_xsim.html -wdm Z:/rrutherford20/CS-401-1-CompArch/MIPS_1/ALU_FINAL/ALU_FINAL.sim/sim_1/behav/xsim/xsim.dir/TestALU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
